version: '2'
services:
    hospital-app:
        image: hospital
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hospital-postgresql:5432/hospital
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hospital-postgresql:
        extends:
            file: postgresql.yml
            service: hospital-postgresql
